### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by phanngt** [hjpotter92/sonyflake-py#1]
How to run this project?

**Comment by hjpotter92** [comment]
@phanngt i was in the process of documenting, but have been otherwise occupied and don't have access to a system.

will update the readme asahp.

**Comment by hjpotter92** [comment]
Added a minimal quickstart to the readme.

**Comment by phanngt** [comment]
Should we create a server instance to maintain Object SonyFlake?

**Comment by hjpotter92** [comment]
> Should we create a server instance to maintain Object SonyFlake? Like SnowFlake server?

There is a thread safe lock inside the class. You can instantiate it as per your server needs. The project itself is a rewrite of the original golang project from sony (<https://github.com/sony/sonyflake>).
